ctfd:
  - templates
  - globals
  - globals2
  - template_polyglot
  - pickle
  - pysh

ports:
  templates:
    - 2000
  globals:
    - 2001
  globals2:
    - 2002
  template_polyglot:
    - 2003
  pickle:
    - 2004
  pysh:
    - 2005
